export const FETCH_PRODUCTS_RELOADING = 'FETCH_PRODUCTS_RELOADING'; 
export const SELLER_RELOADING = 'SELLER_RELOADING'; 
export const SEARCH_RELOADING = 'SEARCH_RELOADING'; 
export const FETCH_PRODUCTS_START = 'FETCH_PRODUCTS_START'; 
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS'; 
export const FETCH_PRODUCTS_FAIL = 'FETCH_PRODUCTS_FAIL'; 

export const FETCH_ONEPRODUCT_START = 'FETCH_ONEPRODUCT_START'; 
export const FETCH_ONEPRODUCT_SUCCESS = 'FETCH_ONEPRODUCT_SUCCESS'; 
export const FETCH_ONEPRODUCT_FAIL = 'FETCH_ONEPRODUCT_FAIL'; 

export const CART_ADD_ITEM = 'CART_ADD_ITEM'; 
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM'; 
export const CART_EMPTY_ITEM = 'CART_EMPTY_ITEM'; 
export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS'; 
export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD'; 

export const USER_SIGNIN_RESETSIGNMSGERROR = 'USER_SIGNIN_RESETSIGNMSGERROR';
export const USER_SIGNIN_START = 'USER_SIGNIN_START';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';
export const USER_REGISTER_START = 'USER_REGISTER_START';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';
export const USER_SIGNIN_RESETMSGERROR = 'USER_SIGNIN_RESETMSGERROR';
export const USER_DETILS_START = 'USER_DETILS_START';
export const USER_DETILS_SUCCESS = 'USER_DETILS_SUCCESS';
export const USER_DETILS_FAIL = 'USER_DETILS_FAIL';
export const USER_UPDATE_PROFILE_RESETMSGERROR = 'USER_UPDATE_PROFILE_RESETMSGERROR';
export const USER_UPDATE_PROFILE_START = 'USER_UPDATE_PROFILE_START';
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS';
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL';
export const USER_ADDRESS_MAP_CONFIRM = 'USER_ADDRESS_MAP_CONFIRM';
export const USER_SIGNOUT = 'USER_SIGNOUT';

export const ORDER_CREATE_START = 'ORDER_CREATE_START';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL';
export const ORDER_CREATE_RESET = 'ORDER_CREATE_RESET';

export const ORDER_DETAILS_START = 'ORDER_DETAILS_START';
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS';
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL';

export const ORDER_PAY_START = 'ORDER_PAY_START';
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS';
export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL';
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET';

export const ORDER_MINE_LIST_RELOADING = 'ORDER_MINE_LIST_RELOADING';
export const ORDER_MINE_LIST_START = 'ORDER_MINE_LIST_START';
export const ORDER_MINE_LIST_SUCCESS = 'ORDER_MINE_LIST_SUCCESS';
export const ORDER_MINE_LIST_FAIL = 'ORDER_MINE_LIST_FAIL';
export const ORDER_LIST_START = 'ORDER_LIST_START';
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS';
export const ORDER_LIST_FAIL = 'ORDER_LIST_FAIL';
export const ORDER_DELETE_START = 'ORDER_DELETE_START';
export const ORDER_DELETE_SUCCESS = 'ORDER_DELETE_SUCCESS';
export const ORDER_DELETE_FAIL = 'ORDER_DELETE_FAIL';
export const ORDER_DELETE_RESET = 'ORDER_DELETE_RESET';

export const PRODUCT_CREATE_START = 'PRODUCT_CREATE_START';
export const PRODUCT_CREATE_SUCCESS = 'PRODUCT_CREATE_SUCCESS';
export const PRODUCT_CREATE_FAIL = 'PRODUCT_CREATE_FAIL';
export const PRODUCT_CREATE_RESET = 'PRODUCT_CREATE_RESET';

export const PRODUCT_UPDATE_START = 'PRODUCT_UPDATE_START';
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS';
export const PRODUCT_UPDATE_FAIL = 'PRODUCT_UPDATE_FAIL';
export const PRODUCT_CHANGE_STATUS = 'PRODUCT_CHANGE_STATUS';

export const PRODUCT_DELETE_START = 'PRODUCT_DELETE_START';
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS';
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL';

export const USERS_LIST_START = 'USERS_LIST_START';
export const USERS_LIST_SUCCESS = 'USERS_LIST_SUCCESS';
export const USERS_LIST_FAIL = 'USERS_LIST_FAIL';

export const USERS_DELETE_RESET = 'USERS_DELETE_RESET';
export const USERS_DELETE_START = 'USERS_DELETE_START';
export const USERS_DELETE_SUCCESS = 'USERS_DELETE_SUCCESS';
export const USERS_DELETE_FAIL = 'USERS_DELETE_FAIL';

export const USERS_UPDATE_START = 'USERS_UPDATE_START';
export const USERS_UPDATE_SUCCESS = 'USERS_UPDATE_SUCCESS';
export const USERS_UPDATE_FAIL = 'USERS_UPDATE_FAIL';

export const HOME_SCREEN_LIST_RELOADING = 'HOME_SCREEN_LIST_RELOADING';
export const HOME_SCREEN_LIST_START = 'HOME_SCREEN_LIST_START';
export const HOME_SCREEN_LIST_SUCCESS = 'HOME_SCREEN_LIST_SUCCESS';
export const HOME_SCREEN_LIST_FAIL = 'HOME_SCREEN_LIST_FAIL';

export const CATEGORY_LIST_START = 'CATEGORY_LIST_START';
export const CATEGORY_LIST_SUCCESS = 'CATEGORY_LIST_SUCCESS';
export const CATEGORY_LIST_FAIL = 'CATEGORY_LIST_FAIL';

export const REVIEW_CREATE_START = 'REVIEW_CREATE_START';
export const REVIEW_CREATE_SUCCESS = 'REVIEW_CREATE_SUCCESS';
export const REVIEW_CREATE_FAIL = 'REVIEW_CREATE_FAIL';
export const REVIEW_CREATE_RESET = 'REVIEW_CREATE_RESET';